name: Security Audit

on:
  schedule:
    - cron: '0 8 * * 1'  # Jeden Montag um 08:00 UTC
  workflow_dispatch:      # Manuell auslösbar
  pull_request:
    branches: 
      - main
      - dev 
  push:
    branches:
      - main
      - dev

jobs:
  pip-audit:
    permissions:
        contents: read
        pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install pip-audit
        run: |
          pip install --upgrade pip-audit

      - name: Run pip-audit
        run: |
          pip-audit --format json
